-- Commercial-gym exercise library.
--
-- Expands the seeded library (119 exercises drawn from Karl's own splits and
-- athlete logs, almost entirely machines and cables) into full coverage across
-- every implement an athlete might find: barbell, dumbbell, cable, selectorised
-- machine, plate-loaded / Hammer Strength, Smith machine, bodyweight, band and
-- kettlebell. Plus the two categories the spec calls for that were empty:
-- Running Strength and Plyometric.
--
-- ADD ONLY — never rename, never reclassify.
--
-- Exercise NAME is the join key between a prescription and an athlete's
-- history: training_session_logs matches on it, and the portal's swap and PB
-- logic key off it too. Renaming "Bench Press" would orphan every set ever
-- logged against it. ON CONFLICT (match_key) DO NOTHING guarantees the 119
-- exercises already in use are left exactly as they are.
--
-- Regenerate with: python3 scripts/build-exercise-library.py
-- Rollback: rollback/20260815000007_commercial_exercise_library_down.sql

begin;

insert into public.exercise_library (name, match_key, category, muscle_group, equipment, created_by)
select v.name,
       -- Same expression as the original seed migration, and the same as the
       -- portal's priorityMatchKey(), so identity never drifts.
       btrim(regexp_replace(lower(btrim(v.name)), '[^a-z0-9]+', ' ', 'g')),
       v.category, v.category, v.equipment, 'library-v2'
from (values
  ('Barbell Bench Press','Chest','Barbell'),
  ('Barbell Decline Bench Press','Chest','Barbell'),
  ('Barbell Floor Press','Chest','Barbell'),
  ('Barbell Pin Press','Chest','Barbell'),
  ('Barbell Pullover','Chest','Barbell'),
  ('Dumbbell Bench Press','Chest','Dumbbell'),
  ('Dumbbell Decline Press','Chest','Dumbbell'),
  ('Dumbbell Floor Press','Chest','Dumbbell'),
  ('Dumbbell Pullover','Chest','Dumbbell'),
  ('Single Arm Dumbbell Press','Chest','Dumbbell'),
  ('Cable Crossover','Chest','Cable'),
  ('High to Low Cable Fly','Chest','Cable'),
  ('Low to High Cable Fly','Chest','Cable'),
  ('Single Arm Cable Fly','Chest','Cable'),
  ('Standing Cable Press','Chest','Cable'),
  ('Chest Press Machine','Chest','Machine'),
  ('Seated Chest Press Machine','Chest','Machine'),
  ('Decline Chest Press Machine','Chest','Machine'),
  ('Converging Chest Press','Chest','Machine'),
  ('Plate Loaded Chest Press','Chest','Plate-loaded'),
  ('Plate Loaded Incline Press','Chest','Plate-loaded'),
  ('Plate Loaded Decline Press','Chest','Plate-loaded'),
  ('Hammer Strength Chest Press','Chest','Plate-loaded'),
  ('Hammer Strength Incline Press','Chest','Plate-loaded'),
  ('Smith Machine Bench Press','Chest','Smith machine'),
  ('Smith Machine Decline Press','Chest','Smith machine'),
  ('Push Up','Chest','Bodyweight'),
  ('Incline Push Up','Chest','Bodyweight'),
  ('Decline Push Up','Chest','Bodyweight'),
  ('Deficit Push Up','Chest','Bodyweight'),
  ('Weighted Push Up','Chest','Bodyweight'),
  ('Chest Dip','Chest','Bodyweight'),
  ('Weighted Chest Dip','Chest','Bodyweight'),
  ('Banded Push Up','Chest','Band'),
  ('Band Chest Press','Chest','Band'),
  ('Barbell Row','Back','Barbell'),
  ('Pendlay Row','Back','Barbell'),
  ('Yates Row','Back','Barbell'),
  ('Barbell Shrug','Back','Barbell'),
  ('T Bar Row','Back','Barbell'),
  ('Barbell Deadlift','Back','Barbell'),
  ('Sumo Deadlift','Back','Barbell'),
  ('Rack Pull','Back','Barbell'),
  ('Trap Bar Deadlift','Back','Barbell'),
  ('Single Arm Dumbbell Row','Back','Dumbbell'),
  ('Chest Supported Dumbbell Row','Back','Dumbbell'),
  ('Dumbbell Shrug','Back','Dumbbell'),
  ('Dumbbell Pullover to Row','Back','Dumbbell'),
  ('Straight Arm Pulldown','Back','Cable'),
  ('Single Arm Cable Row','Back','Cable'),
  ('Cable Shrug','Back','Cable'),
  ('Half Kneeling Cable Pulldown','Back','Cable'),
  ('Reverse Grip Cable Row','Back','Cable'),
  ('Assisted Chin Up','Back','Machine'),
  ('Reverse Grip Pulldown','Back','Machine'),
  ('Machine Pullover','Back','Machine'),
  ('Machine Shrug','Back','Machine'),
  ('Seated Row Machine','Back','Machine'),
  ('Plate Loaded Row','Back','Plate-loaded'),
  ('Plate Loaded Pulldown','Back','Plate-loaded'),
  ('Hammer Strength Row','Back','Plate-loaded'),
  ('Hammer Strength High Row','Back','Plate-loaded'),
  ('Iso Lateral Row','Back','Plate-loaded'),
  ('Smith Machine Row','Back','Smith machine'),
  ('Chin Up','Back','Bodyweight'),
  ('Neutral Grip Pull Up','Back','Bodyweight'),
  ('Wide Grip Pull Up','Back','Bodyweight'),
  ('Weighted Pull Up','Back','Bodyweight'),
  ('Inverted Row','Back','Bodyweight'),
  ('Ring Row','Back','Bodyweight'),
  ('Banded Pulldown','Back','Band'),
  ('Banded Row','Back','Band'),
  ('Barbell Overhead Press','Shoulders','Barbell'),
  ('Standing Barbell Press','Shoulders','Barbell'),
  ('Push Press','Shoulders','Barbell'),
  ('Barbell Upright Row','Shoulders','Barbell'),
  ('Behind the Neck Press','Shoulders','Barbell'),
  ('Arnold Press','Shoulders','Dumbbell'),
  ('Seated Dumbbell Shoulder Press','Shoulders','Dumbbell'),
  ('Dumbbell Front Raise','Shoulders','Dumbbell'),
  ('Dumbbell Rear Delt Fly','Shoulders','Dumbbell'),
  ('Dumbbell Upright Row','Shoulders','Dumbbell'),
  ('Dumbbell Y Raise','Shoulders','Dumbbell'),
  ('Leaning Cable Lateral Raise','Shoulders','Cable'),
  ('Cable Upright Raise','Shoulders','Cable'),
  ('Cable Front Raise','Shoulders','Cable'),
  ('Cable Rope Face Pull','Shoulders','Cable'),
  ('Single Arm Cable Lateral Raise','Shoulders','Cable'),
  ('Cable External Rotation','Shoulders','Cable'),
  ('Machine Rear Delt Fly','Shoulders','Machine'),
  ('Machine Overhead Press','Shoulders','Machine'),
  ('Plate Loaded Shoulder Press','Shoulders','Plate-loaded'),
  ('Hammer Strength Shoulder Press','Shoulders','Plate-loaded'),
  ('Smith Machine Shoulder Press','Shoulders','Smith machine'),
  ('Band Pull Apart','Shoulders','Band'),
  ('Banded External Rotation','Shoulders','Band'),
  ('Banded Lateral Raise','Shoulders','Band'),
  ('Pike Push Up','Shoulders','Bodyweight'),
  ('EZ Bar Curl','Biceps','Barbell'),
  ('Barbell Preacher Curl','Biceps','Barbell'),
  ('Barbell Drag Curl','Biceps','Barbell'),
  ('Barbell Wrist Curl','Biceps','Barbell'),
  ('Dumbbell Concentration Curl','Biceps','Dumbbell'),
  ('Dumbbell Preacher Curl','Biceps','Dumbbell'),
  ('Dumbbell Spider Curl','Biceps','Dumbbell'),
  ('Dumbbell Zottman Curl','Biceps','Dumbbell'),
  ('Dumbbell Wrist Curl','Biceps','Dumbbell'),
  ('Dumbbell Reverse Wrist Curl','Biceps','Dumbbell'),
  ('Seated Dumbbell Curl','Biceps','Dumbbell'),
  ('Cable Hammer Curl','Biceps','Cable'),
  ('Cable Preacher Curl','Biceps','Cable'),
  ('High Cable Curl','Biceps','Cable'),
  ('Cable Reverse Curl','Biceps','Cable'),
  ('Machine Bicep Curl','Biceps','Machine'),
  ('Farmer Carry','Biceps','Other'),
  ('Plate Pinch Hold','Biceps','Other'),
  ('Dead Hang','Biceps','Other'),
  ('Close Grip Bench Press','Triceps','Barbell'),
  ('EZ Bar Skull Crusher','Triceps','Barbell'),
  ('Barbell JM Press','Triceps','Barbell'),
  ('Dumbbell Overhead Extension','Triceps','Dumbbell'),
  ('Dumbbell Skull Crusher','Triceps','Dumbbell'),
  ('Dumbbell Kickback','Triceps','Dumbbell'),
  ('Single Arm Dumbbell Extension','Triceps','Dumbbell'),
  ('Cable Rope Pushdown','Triceps','Cable'),
  ('Single Arm Cable Pushdown','Triceps','Cable'),
  ('Reverse Grip Pushdown','Triceps','Cable'),
  ('Cable Crossbody Extension','Triceps','Cable'),
  ('Machine Tricep Extension','Triceps','Machine'),
  ('Assisted Tricep Dip','Triceps','Machine'),
  ('Bench Dip','Triceps','Bodyweight'),
  ('Diamond Push Up','Triceps','Bodyweight'),
  ('Tricep Dip','Triceps','Bodyweight'),
  ('Back Squat','Quads','Barbell'),
  ('Front Squat','Quads','Barbell'),
  ('High Bar Back Squat','Quads','Barbell'),
  ('Low Bar Back Squat','Quads','Barbell'),
  ('Pause Squat','Quads','Barbell'),
  ('Barbell Walking Lunge','Quads','Barbell'),
  ('Barbell Split Squat','Quads','Barbell'),
  ('Barbell Step Up','Quads','Barbell'),
  ('Zercher Squat','Quads','Barbell'),
  ('Barbell Box Squat','Quads','Barbell'),
  ('Goblet Squat','Quads','Dumbbell'),
  ('Dumbbell Walking Lunge','Quads','Dumbbell'),
  ('Dumbbell Reverse Lunge','Quads','Dumbbell'),
  ('Dumbbell Lateral Lunge','Quads','Dumbbell'),
  ('Dumbbell Curtsy Lunge','Quads','Dumbbell'),
  ('Dumbbell Front Squat','Quads','Dumbbell'),
  ('Dumbbell Deficit Split Squat','Quads','Dumbbell'),
  ('Leg Press (45 degree)','Quads','Machine'),
  ('Horizontal Leg Press','Quads','Machine'),
  ('Single Leg Press','Quads','Machine'),
  ('Pendulum Squat','Quads','Machine'),
  ('V Squat Machine','Quads','Machine'),
  ('Belt Squat','Quads','Machine'),
  ('Plate Loaded Hack Squat','Quads','Plate-loaded'),
  ('Plate Loaded Leg Press','Quads','Plate-loaded'),
  ('Hammer Strength Leg Press','Quads','Plate-loaded'),
  ('Smith Machine Split Squat','Quads','Smith machine'),
  ('Smith Machine Front Squat','Quads','Smith machine'),
  ('Bodyweight Squat','Quads','Bodyweight'),
  ('Sissy Squat','Quads','Bodyweight'),
  ('Wall Sit','Quads','Bodyweight'),
  ('Spanish Squat','Quads','Bodyweight'),
  ('Sled Push','Quads','Other'),
  ('Prowler Push','Quads','Other'),
  ('Landmine Squat','Quads','Other'),
  ('Conventional Deadlift','Hamstrings','Barbell'),
  ('Stiff Leg Deadlift','Hamstrings','Barbell'),
  ('Deficit Deadlift','Hamstrings','Barbell'),
  ('Barbell Good Morning','Hamstrings','Barbell'),
  ('Snatch Grip Romanian Deadlift','Hamstrings','Barbell'),
  ('Dumbbell Stiff Leg Deadlift','Hamstrings','Dumbbell'),
  ('Single Leg Dumbbell RDL','Hamstrings','Dumbbell'),
  ('Dumbbell Good Morning','Hamstrings','Dumbbell'),
  ('Standing Leg Curl','Hamstrings','Machine'),
  ('Glute Ham Raise','Hamstrings','Machine'),
  ('Reverse Hyperextension','Hamstrings','Machine'),
  ('Prone Leg Curl','Hamstrings','Machine'),
  ('Plate Loaded Leg Curl','Hamstrings','Plate-loaded'),
  ('Hammer Strength Leg Curl','Hamstrings','Plate-loaded'),
  ('Cable Romanian Deadlift','Hamstrings','Cable'),
  ('Cable Leg Curl','Hamstrings','Cable'),
  ('Slider Leg Curl','Hamstrings','Bodyweight'),
  ('Swiss Ball Leg Curl','Hamstrings','Bodyweight'),
  ('Banded Hamstring Curl','Hamstrings','Band'),
  ('Barbell Glute Bridge','Glutes','Barbell'),
  ('Barbell Frog Pump','Glutes','Barbell'),
  ('Landmine Hip Thrust','Glutes','Barbell'),
  ('Dumbbell Hip Thrust','Glutes','Dumbbell'),
  ('Dumbbell Glute Bridge','Glutes','Dumbbell'),
  ('Dumbbell Sumo Deadlift','Glutes','Dumbbell'),
  ('Dumbbell Single Leg Hip Thrust','Glutes','Dumbbell'),
  ('Cable Standing Abduction','Glutes','Cable'),
  ('Cable Sumo Squat','Glutes','Cable'),
  ('Cable Hip Extension','Glutes','Cable'),
  ('Seated Abduction Machine','Glutes','Machine'),
  ('Glute Drive Machine','Glutes','Machine'),
  ('Standing Glute Kickback Machine','Glutes','Machine'),
  ('Hip Extension Machine','Glutes','Machine'),
  ('Plate Loaded Hip Thrust','Glutes','Plate-loaded'),
  ('Plate Loaded Glute Bridge','Glutes','Plate-loaded'),
  ('Single Leg Glute Bridge','Glutes','Bodyweight'),
  ('Frog Pump','Glutes','Bodyweight'),
  ('Fire Hydrant','Glutes','Bodyweight'),
  ('Bodyweight Hip Thrust','Glutes','Bodyweight'),
  ('Banded Glute Bridge','Glutes','Band'),
  ('Banded Monster Walk','Glutes','Band'),
  ('Banded Clamshell','Glutes','Band'),
  ('Kettlebell Sumo Deadlift','Glutes','Kettlebell'),
  ('Kettlebell Goblet Bridge','Glutes','Kettlebell'),
  ('Donkey Calf Raise','Calves','Machine'),
  ('Standing Calf Raise Machine','Calves','Machine'),
  ('Seated Calf Raise Machine','Calves','Machine'),
  ('Smith Machine Calf Raise','Calves','Machine'),
  ('Dumbbell Standing Calf Raise','Calves','Dumbbell'),
  ('Single Leg Dumbbell Calf Raise','Calves','Dumbbell'),
  ('Barbell Calf Raise','Calves','Barbell'),
  ('Single Leg Calf Raise','Calves','Bodyweight'),
  ('Bent Knee Calf Raise','Calves','Bodyweight'),
  ('Eccentric Calf Raise','Calves','Bodyweight'),
  ('Calf Raise off Step','Calves','Bodyweight'),
  ('Plate Loaded Calf Raise','Calves','Plate-loaded'),
  ('Plank','Core','Bodyweight'),
  ('Side Plank','Core','Bodyweight'),
  ('Dead Bug','Core','Bodyweight'),
  ('Bird Dog','Core','Bodyweight'),
  ('Hollow Hold','Core','Bodyweight'),
  ('V Up','Core','Bodyweight'),
  ('Toes to Bar','Core','Bodyweight'),
  ('Mountain Climber','Core','Bodyweight'),
  ('Reverse Crunch','Core','Bodyweight'),
  ('Bicycle Crunch','Core','Bodyweight'),
  ('L Sit','Core','Bodyweight'),
  ('Ab Wheel Rollout','Core','Bodyweight'),
  ('Pallof Press','Core','Cable'),
  ('Cable Woodchop','Core','Cable'),
  ('Cable Reverse Woodchop','Core','Cable'),
  ('Half Kneeling Pallof Press','Core','Cable'),
  ('Cable Side Bend','Core','Cable'),
  ('Dumbbell Side Bend','Core','Dumbbell'),
  ('Dumbbell Russian Twist','Core','Dumbbell'),
  ('Suitcase Carry','Core','Dumbbell'),
  ('Torso Rotation Machine','Core','Machine'),
  ('Kettlebell Windmill','Core','Kettlebell'),
  ('Kettlebell Turkish Get Up','Core','Kettlebell'),
  ('Landmine Rotation','Core','Other'),
  ('Medicine Ball Slam','Core','Other'),
  ('Medicine Ball Russian Twist','Core','Other'),
  ('Single Leg Calf Raise Isometric','Running Strength','Bodyweight'),
  ('Heel Walk','Running Strength','Bodyweight'),
  ('Toe Walk','Running Strength','Bodyweight'),
  ('Single Leg Balance','Running Strength','Bodyweight'),
  ('Single Leg RDL Bodyweight','Running Strength','Bodyweight'),
  ('Step Down Eccentric','Running Strength','Bodyweight'),
  ('Hip Airplane','Running Strength','Bodyweight'),
  ('Single Leg Bridge Hold','Running Strength','Bodyweight'),
  ('Foot Doming (Short Foot)','Running Strength','Bodyweight'),
  ('Calf Raise Isometric Hold','Running Strength','Bodyweight'),
  ('Banded Tibialis Raise','Running Strength','Band'),
  ('Banded Hip Abduction Standing','Running Strength','Band'),
  ('Banded Terminal Knee Extension','Running Strength','Band'),
  ('Banded Ankle Eversion','Running Strength','Band'),
  ('Banded Ankle Inversion','Running Strength','Band'),
  ('Weighted Step Down','Running Strength','Dumbbell'),
  ('Suitcase Carry Single Arm','Running Strength','Dumbbell'),
  ('Dumbbell Single Leg Calf Raise Slow Eccentric','Running Strength','Dumbbell'),
  ('Seated Tibialis Machine','Running Strength','Machine'),
  ('Adductor Isometric Squeeze','Running Strength','Machine'),
  ('Copenhagen Side Plank Bent Knee','Running Strength','Other'),
  ('Nordic Hamstring Eccentric','Running Strength','Other'),
  ('Sled Drag Backward','Running Strength','Other'),
  ('Hill Sprint Strength','Running Strength','Other'),
  ('Box Jump','Plyometric','Bodyweight'),
  ('Depth Jump','Plyometric','Bodyweight'),
  ('Broad Jump','Plyometric','Bodyweight'),
  ('Pogo Hop','Plyometric','Bodyweight'),
  ('Single Leg Pogo','Plyometric','Bodyweight'),
  ('Ankle Hop','Plyometric','Bodyweight'),
  ('Tuck Jump','Plyometric','Bodyweight'),
  ('Split Jump','Plyometric','Bodyweight'),
  ('Bounding','Plyometric','Bodyweight'),
  ('Single Leg Bound','Plyometric','Bodyweight'),
  ('Lateral Bound','Plyometric','Bodyweight'),
  ('Skater Jump','Plyometric','Bodyweight'),
  ('Hurdle Hop','Plyometric','Bodyweight'),
  ('Single Leg Box Jump','Plyometric','Bodyweight'),
  ('Countermovement Jump','Plyometric','Bodyweight'),
  ('Drop Landing','Plyometric','Bodyweight'),
  ('Squat Jump','Plyometric','Bodyweight'),
  ('Continuous Long Jump','Plyometric','Bodyweight'),
  ('A Skip','Plyometric','Bodyweight'),
  ('B Skip','Plyometric','Bodyweight'),
  ('High Knees','Plyometric','Bodyweight'),
  ('Medicine Ball Chest Pass','Plyometric','Other'),
  ('Medicine Ball Overhead Throw','Plyometric','Other'),
  ('Medicine Ball Rotational Throw','Plyometric','Other'),
  ('Kettlebell Swing Explosive','Plyometric','Other'),
  ('Hang Power Clean','Plyometric','Barbell'),
  ('Power Clean','Plyometric','Barbell'),
  ('Push Jerk','Plyometric','Barbell'),
  ('Barbell Jump Squat','Plyometric','Barbell')
) as v(name, category, equipment)
on conflict (match_key) do nothing;

commit;
