-- Durable, server-only inbox for Strava webhook events. Strava expects a 2xx
-- response within two seconds, so the webhook stores the event in one request;
-- the athlete's next protected Strava read applies it to the activity cache.

create table if not exists public.strava_webhook_events (
  id bigint generated by default as identity primary key,
  subscription_id bigint,
  owner_id bigint not null,
  object_type text not null,
  object_id bigint not null,
  aspect_type text not null,
  updates jsonb not null default '{}'::jsonb,
  event_time timestamptz,
  athlete_code text,
  processed_at timestamptz,
  attempts integer not null default 0,
  last_error text,
  received_at timestamptz not null default now()
);

create index if not exists strava_webhook_events_owner_idx
  on public.strava_webhook_events (owner_id, processed_at);
create index if not exists strava_webhook_events_pending_idx
  on public.strava_webhook_events (processed_at, received_at)
  where processed_at is null;

alter table public.strava_webhook_events enable row level security;
revoke all on table public.strava_webhook_events from anon, authenticated;
grant select, insert, update, delete on table public.strava_webhook_events to service_role;
grant usage, select on sequence public.strava_webhook_events_id_seq to service_role;

comment on table public.strava_webhook_events is
  'Durable server-only inbox used to acknowledge Strava webhooks quickly and process cache invalidation safely.';
